import Head from 'next/head';
import { ReactCompareSlider, ReactCompareSliderImage } from 'react-compare-slider';

export default function Home() {
  return (
    <>
      <Head>
        <title>React Compare Slider SSR Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ReactCompareSlider
          itemOne={
            <ReactCompareSliderImage src="https://raw.githubusercontent.com/nerdyman/stuff/main/libs/react-compare-slider/demo-images/e2e-test-1.png" />
          }
          itemTwo={
            <ReactCompareSliderImage src="https://raw.githubusercontent.com/nerdyman/stuff/main/libs/react-compare-slider/demo-images/e2e-test-2.png" />
          }
        />
      </main>
    </>
  );
}
