name: "Bundlephobia"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bundlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: carlesnunez/check-my-bundlephobia@v1.6.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          strict: true
          threshold: 10000
          ignore-dev-dependencies: false
