name: Review

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout repo
        uses: actions/checkout@v6

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⚒️ Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      # see https://github.com/actions/setup-node/issues/1137
      - name: 📂 Create pnpm cache directory
        shell: bash
        run: mkdir -vp $(pnpm store path --silent)

      - name: 🧑‍⚕️ React Doctor
        uses: millionco/react-doctor@main
        with:
          diff: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 24
